study(title="Plasma Clouds", overlay=true)
// Oscar Campbell - 2014-07-08
// Funkar bra i 4h samt 1D - tuna mer.

// Idea:
// Loop a whole range of different lookback lengths, measure 0.5 and other
// possible good fibs. Loop back for T time and collect those values to (offset)
// Those that does actual turns of P get's +1 score. All are summed for each
// price (with thresholds for P spread at different levels (longer timespan,
// bigger spread ofc.). Now we get a weight for each price level as to likelihood
// of it being a turning point
// This coupled with other indications of "reversal readiness" makes the case.


lblA = input(30, minval=1)
lblB = input(50, minval=1)
lblC = input(105, minval=1)
//displacement = input(7, minval=1)

fiblevSpec(sh, sl, hlen, llen, mult, ofs, thresh) =>
    lowpoint = lowest(sl[ofs], llen)
    height = highest(sh[ofs], hlen) - lowpoint
    out = lowpoint + height * mult
    mid = (sh + sl) / 2  // Note - compare point is "now", while calc point is ofsetted
    abs(out - mid) / mid < thresh ? out : na

fiblev(len, mult) => fiblevSpec(close, close, len, len, mult, 1, 0.99)
fiblevHL(len, mult) => fiblevSpec(high, low, len, len, mult, 1, 0.99)
fiblevS(hlen, llen, mult) => fiblevSpec(close, close, hlen, llen, mult, 1, 0.99)
fiblevSHL(hlen, llen,  mult) => fiblevSpec(high, low, hlen, llen, mult, 1, 0.99)

//0.382
//0.5
//0.681
//0.764
//0.864
//1.27
//1.382
//1.618


plot(fiblev(lblB, 1.618), color=red, offset=10, style = circles)

// // // // //
// // // // //
// // // // //
s138Ep1 = plot(fiblevS(8, 21, 1.382-0.002), color=purple, offset= 10, style=circles)  // A-1.3182+5 - KLOCKREN! (finex-test, 140708) Stoppar toppar på väg upp..
s138Ep2 = plot(fiblevS(21, 8, 1.382-0.002), color=purple, offset= 10, style=circles)  // A-1.3182+5 - KLOCKREN! (finex-test, 140708) Stoppar toppar på väg upp..
fill(s138Ep1, s138Ep2, color=purple, transp=90)

s138p1 = plot(fiblevHL(lblA, 1.382), color=purple, offset= 5, style=circles)  // A-1.3182+5 - KLOCKREN! (finex-test, 140708) Stoppar toppar på väg upp..
s138p2 = plot(fiblev(lblA, 1.382), color=purple, offset= 5, style=circles)  // A-1.3182+5 - KLOCKREN! (finex-test, 140708) Stoppar toppar på väg upp..
fill(s138p1, s138p2, color=purple, transp=90)

s138Bp1 = plot(fiblevS(lblB, lblA, 1.382), color=purple, offset= 8, style=circles)  // A-1.3182+5 - KLOCKREN! (finex-test, 140708) Stoppar toppar på väg upp..
s138Bp2 = plot(fiblevS(lblA, lblB, 1.382), color=purple, offset= 8, style=circles)  // A-1.3182+5 - KLOCKREN! (finex-test, 140708) Stoppar toppar på väg upp..
fill(s138Bp1, s138Bp2, color=purple, transp=90)

s138Cp1 = plot(fiblevSHL(lblB, lblA, 1.382+0.005), color=purple, offset= 8, style=circles)  // A-1.3182+5 - KLOCKREN! (finex-test, 140708) Stoppar toppar på väg upp..
s138Cp2 = plot(fiblevSHL(lblA, lblB, 1.382+0.005), color=purple, offset= 8, style=circles)  // A-1.3182+5 - KLOCKREN! (finex-test, 140708) Stoppar toppar på väg upp..
fill(s138Cp1, s138Cp2, color=purple, transp=90)

s138Dp1 = plot(fiblevS(34, 89, 1.382-0.005), color=purple, offset= 16, style=circles)  // A-1.3182+5 - KLOCKREN! (finex-test, 140708) Stoppar toppar på väg upp..
s138Dp2 = plot(fiblevS(89, 34, 1.382-0.005), color=purple, offset= 16, style=circles)  // A-1.3182+5 - KLOCKREN! (finex-test, 140708) Stoppar toppar på väg upp..
fill(s138Dp1, s138Dp2, color=purple, transp=90)
// // // // //
// // // // //
// // // // //

plot(fiblev(lblA, 1.27), color=#ff00ff, offset=34, style = circles)  // Blir en break på någon hill up, visar sen första bump uppe på toppen..

plot(fiblev(lblB, 0.681), offset=0, color=#00ffff, style = circles)
plot(fiblevHL(lblB, 0.681), offset=0, color=#00ffff, style = circles)
plot(fiblevS(lblA, lblB, 0.681), offset=0, color=#00ffff, style = circles)
plot(fiblevS(lblB, lblA, 0.681), offset=0, color=#00ffff, style = circles)

//plot(abs(up1 - close[-20])/close > 0.02 ? na : up1, offset=lblC / 3 + lblC / 2, color=yellow, style = circles)
plot(fiblev(60, 0.5), offset= 60, color=yellow, style = circles)

// // // // //
// // // // //
// // // // //

b50Ap1 = plot(fiblev(lblB, 0.5), offset=1, color=blue, style=circles)
b50Ap2 = plot(fiblevHL(lblB, 0.5), offset=1, color=blue, style=circles)
fill(b50Ap1, b50Ap2, color=blue, transp=90)

b50Bp1 = plot(fiblevS(lblB, lblA, 0.5+0.01), offset=1, color=#0000aa, style=circles)
b50Bp2 = plot(fiblevS(lblA, lblB, 0.5+0.01), offset=1, color=#0000aa, style=circles)
fill(b50Bp1, b50Bp2, color=blue, transp=90)

b50Cp1 = plot(fiblevSHL(lblB, lblA, 0.5-0.01), offset=1, color=#0000aa, style=circles)
b50Cp2 = plot(fiblevSHL(lblA, lblB, 0.5-0.01), offset=1, color=#0000aa, style=circles)
fill(b50Cp1, b50Cp2, color=blue, transp=90)

b50Dp1 = plot(fiblevS(10, 6, 0.5), offset=0, color=#7777ff, style=line)
b50Dp2 = plot(fiblevS(6, 10, 0.5), offset=0, color=#7777ff, style=line)
fill(b50Dp1, b50Dp2, color=blue, transp=90)

b50Ep1 = plot(fiblevSHL(144, 89, 0.5-0.005), offset=21, color=#0000aa, style=circles)
b50Ep2 = plot(fiblevSHL(89, 144, 0.5-0.005), offset=21, color=#0000aa, style=circles)
fill(b50Ep1, b50Ep2, color=blue, transp=90)
b50E2p1 = plot(fiblevSHL(55, 89, 0.5+0.005), offset=34, color=#0000aa, style=circles)
b50E2p2 = plot(fiblevSHL(89, 55, 0.5+0.005), offset=34, color=#0000aa, style=circles)
fill(b50E2p1, b50Ep2, color=blue, transp=90)

// // // // //
// // // // //
// // // // //

a50p1 = plot(fiblev(lblA, 0.5), offset=0, color=gray, style=circles)   // SUPPORTS UNDER HILLS UP (se A-1.382+5)
a50p2 = plot(fiblevHL(lblA, 0.5), offset=0, color=gray, style=circles)   // SUPPORTS UNDER HILLS UP (se A-1.382+5)
fill(a50p1, a50p2, color=gray, transp=90)

plot(fiblev(lblB, 0.382), offset=1, color=green, style = circles)


plot(fiblev(lblB, -0.15), offset=1, color=#ff5500, style=circles)

sub3 = fiblev(lblA, -0.127)
plot(sub3, color=#aa0050, offset=0, style = circles)
s4Ap1 = plot(fiblevS(10, lblA, -0.127),color=#aa0050, offset=0, style = circles)
s4Ap2 = plot(fiblevS(lblA, 10, -0.127),color=#aa0050, offset=0, style = circles)
fill(s4Ap1, s4Ap2, color=#aa0050, transp=90)

s3p1 = plot(sub3, color=purple, offset=6, style=circles)
s3p2 = plot(fiblevHL(lblA, -0.27), color=purple, offset=6, style=circles)
fill(s3p1, s3p2, color=purple, transp=90)

//plot(fiblev(lblB, -0.27), color=purple, offset=6, style = cross)
//plot(fiblev(lblA, -0.681), color=purple, offset=6, style = cross)
//plot(fiblev(lblA, -0.764), color=red, offset=lblB / 2, style = circles)

//plot(fiblevHL(lblA, -0.5), color=#ff00ff, offset=5, style = line)
//plot(sub1 / close < 0.90 ? na :sub1, color=red, offset=21, style = circles)
sub2 = fiblev(lblA, -0.864)
s1p1 = plot(fiblev(13, -0.5), color=red, offset=10, style = circles)
s2p2 = plot(fiblev(13, -0.864), color=red, offset=10, style = circles)

fill(s1p1, s2p2, color=red, transp=90)
