study("X-Market HL-Delta")

hfinex = security('BITFINEX:BTCUSD', period, high)
hchina = security('BTCCHINA:BTCCNY / FX:USDCNH', period, high)
hhuobi_pre = security('HUOBI:BTCCNY / FX:USDCNH', period, high)
hhuobi = min(hchina*1.04, na(hhuobi_pre) == 0 ? hhuobi_pre : hchina)   // kill rogue prices (huobi 140626)

hbtce = security('BTCE:BTCUSD', period, high)
hstamp = security('BITSTAMP:BTCUSD', period, high)

lfinex = security('BITFINEX:BTCUSD', period, low)
lchina = security('BTCCHINA:BTCCNY / FX:USDCNH', period, low)
lhuobi_pre = security('HUOBI:BTCCNY / FX:USDCNH', period, low)
lhuobi = na(lhuobi_pre) == 0 ? lhuobi_pre : lchina
lbtce = security('BTCE:BTCUSD', period, low)
lstamp = security('BITSTAMP:BTCUSD', period, low)

lchinamix = (lchina + lhuobi) / 2
hchinamix = (hchina + hhuobi) / 2

lcenter = lstamp
hcenter = hstamp
//mcenter = (lcenter + hcenter) / 2

xma (s) => alma(s, 7, 0.85, 9) * 0.8 + s * 0.2

lic = hline(0, color=#333333)
liu20 = hline(10, color=#333333)
lid20 = hline(-10, color=#333333)
hline(5, color=#333333)
hline(-5, color=#333333)
fill(liu20, lic, #00ff00, transp=90)
fill(lid20, lic, #ff0000, transp=90)
//hline(25, color=#dddddd)
//hline(-25, color=#dddddd)

//lavg = (lfinex + lstamp + lchina + lhuobi +lbtce) / 5
//havg = (hfinex + hstamp + hchina + hhuobi +hbtce) / 5
//lavg = (lfinex + lstamp + lchinamix + lbtce) / 4
//havg = (hfinex + hstamp + hchinamix + hbtce) / 4
lavg = (lstamp + lchinamix + lbtce) / 3
havg = (hstamp + hchinamix + hbtce) / 3
//mavg = (lavg + havg) / 2


hd_stamp = hstamp - havg
ld_stamp = lstamp - lavg
md_stamp = (hd_stamp + ld_stamp) / 2

plot(hd_stamp, color=#00ff00)
plot(ld_stamp, color=#ff0000)

plot(alma(hd_stamp, 24 * 5, 0.85, 6), color = #55ff99)
plot(alma(ld_stamp, 24 * 5, 0.85, 6), color = #ff5599)


//plot(havg - hbtce, color=#006600)
//plot(lavg - lbtce, color=#660000)

plot(havg - hchinamix, color=#006600, title="china h")
plot(lavg - lchinamix, color=#660000, title="china l")

hmdelta = ((hstamp - havg) + (havg - hchinamix)) / 2
lmdelta = ((lstamp - lavg) + (lavg - lchinamix)) / 2
mmdelta = (hmdelta + lmdelta) / 2

//plot(hmdelta, color=#336633)
//plot(lmdelta, color=#663333)

//plot(alma(hmdelta, 24, 0.85, 6), color = #55ff99, title="mix avg h")
//plot(alma(lmdelta, 24, 0.85, 6), color = #ff5599, title="mix avg l")
//plot(alma(mmdelta, 24, 0.85, 6), color = #ffffff, title="mix avg  m")
//plot(alma(mmdelta, 24, 0.85, 6), color = #ffffff)

