study("Pin Candle Classifier")

// Notes: In most cases there's not a killer dive _directly_ after the pin. It's better to check
// what's cracking after, to avoid false b/s, and miss some oppurtunities (well, actually.. a limit
// order could be put below or above, thereby kicking off _only_ if the promise of direction is
// fulfilled - yeay!!!)

oc2 = (open + close) / 2
src = oc2

range = high - low
body = abs(close - open)
// essentially, they're the same, in tested liquid markets, might vary in shallow markets... /ORC

hoc = max(open, close)
loc = min(open, close)

hwick = high - hoc
lwick = loc - low
wicks = lwick + hwick

get_baseline(s) =>
    sma(ema(s, 1000), 100)


//hwick_base = get_baseline(hwick)
//lwick_base = get_baseline(lwick)
wick_base = get_baseline(max(hwick, lwick))
wicked_thresh = wick_base * 1 // 0.681 // 1.618   // size vs baseline to be considered pin
hlwicked_ratio = 0.59 * hwick
lhwicked_ratio = 0.3 * lwick

body_base = get_baseline(body)
body_hlf = body_base / 2
body_thresh = 0.03 * body_base

// Note how the threshold is defined as a percentage of a chart-based unit (body_base) - and not hardcoded.
candle_rel_thresh = 0.02 * body_base      // how much may prior candles shadow us to still be considered pin?
candle_rel_count = 5

size_lgc = wicks / body >= 0.4 and range > body_thresh * 8  // we need a minimum candle size to consider it, to avoid micro-up/down false signals
hwick_lgc = (hwick > wicked_thresh or hwick/wick_base > body/body_base) and lwick < hlwicked_ratio
lwick_lgc = (lwick > wicked_thresh or lwick/wick_base > body/body_base) and hwick < lhwicked_ratio

is_moon_lgc = (size_lgc and
            lwick_lgc and
            lowest(loc, candle_rel_count) * (1 + candle_rel_thresh) >= loc)    // no shadowing bodies before

is_dive_lgc = (size_lgc and
            hwick_lgc and
            highest(hoc, candle_rel_count) * (1 - candle_rel_thresh) <= hoc)    // no shadowing bodies before

//is_up_lgc = (hwick < lwick and lowest(min(open, close), 1) >= min(open, close) - body_thresh) or
//    (body > body_base and close > close[1] - body_thresh)

//is_down_lgc = (lwick < hwick and highest(max(open, close), 1) <= max(open, close) + body_thresh) or
//    (body > body_base and close < close[1] + body_thresh)

bgcolor(is_moon_lgc ? #00ff00 : is_dive_lgc ? #ff0000 : na, transp=70)

//plot(body_hlf)
//plot(body_hlf)

//plot(src - body_hlf)
//plot(src + body_hlf)
plot(hwick, color=green, style=circles, linewidth=2)
plot(lwick, color=red, style=circles, linewidth=2)
plot(min(body, 0.023), color=blue, style=circles, linewidth=2)   // limit size for viewing reasons
plot(body_base, color=blue)
plot(body_thresh, color=#bbbbff)
//plot(hwick_base, color=green)
//plot(lwick_base, color=red)
plot(wick_base, color=gray)

//plot(open)
//plot(close, color=#000000)
//plot(high)
//plot(low)
