study("ZARJPYUSD KRIVO TPL IX", shorttitle="KRIX-ZAR/JPY+USD")

src = hlc3
lgthMA1 = input(50)
lgthMA2 = input(200)
lgthMA3 = input(500)

// ZAR
xz1 = security("FX:USDZAR", period, src)
zx1 = security("FX:ZARJPY", period, src)

// JPY
xj1 = security("FX:HKDJPY", period, src)
xj2 = security("FX:AUDJPY", period, src)
xj3 = security("FX:NOKJPY", period, src)
xj4 = security("FX:NZDJPY", period, src)
xj5 = security("FX:CADJPY", period, src)
xj6 = security("FX:CHFJPY", period, src)
xj7 = security("FX:EURJPY", period, src)
xj8 = security("FX:GBPJPY", period, src)
xj9 = security("FX:SEKJPY", period, src)
xj10 = security("FX:ZARJPY", period, src)
xj11 = security("FX:SGDJPY", period, src)
xj12 = security("FX:USDJPY", period, src)
xj13 = security("FX:TRYJPY", period, src)

// USD
xu1=security("FX:AUDUSD", period, src)
xu2=security("FX:EURUSD", period, src)
xu3=security("FX:GBPUSD", period, src)
xu4=security("FX:NZDUSD", period, src)

ux1=security("FX:USDCHF", period, src)
ux2=security("FX:USDDKK", period, src)
ux3=security("FX:USDCAD", period, src)
ux4=security("FX:USDJPY", period, src)
ux5=security("FX:USDPLN", period, src)
ux6=security("FX:USDSEK", period, src)
ux7=security("FX:USDNOK", period, src)
ux8=security("FX:USDHUF", period, src)
ux9=security("FX:USDTRY", period, src)
ux10=security("FX:USDCZK", period, src)
ux11=security("FX:USDSGD", period, src)
ux12=security("FX:USDCNH", period, src)

lgc(s, l) =>
    ma = ema(s, l)
    s >= ma ? 1 : -1
    //d = s - ma
    //d / sma(abs(d), 2000)

nlgc(s, l) => -lgc(s, l)


calc_combed_zar(l) =>
    (nlgc(xz1, l) + lgc(zx1, l)) / 2

calc_combed_jpy(l) =>
    (lgc(xj1, l) + lgc(xj2, l) + lgc(xj3, l) + lgc(xj4, l) +
        lgc(xj5, l) + lgc(xj6, l) + lgc(xj7, l) + lgc(xj8, l) +
        lgc(xj9, l) + lgc(xj10, l) + lgc(xj11, l) + lgc(xj12, l) +
        lgc(xj13, l)) / 13

calc_combed_usd(l) =>
    -(
      (-lgc(xu1, l)) + (-lgc(xu2, l)) + (-lgc(xu3, l)) + (-lgc(xu4, l)) +
        lgc(ux1, l) + lgc(ux2, l) + lgc(ux3, l) + lgc(ux4, l) +
        lgc(ux5, l) + lgc(ux6, l) + lgc(ux7, l) + lgc(ux8, l) +
        lgc(ux9, l) + lgc(ux10, l) + lgc(ux11, l) + lgc(ux12, l)) / 16

div1 = 8
div2 = 2
bal = 0.5
nbal = 1 - bal

zar_t1 = calc_combed_zar(lgthMA1) / div1
zar_t2 = calc_combed_zar(lgthMA2) / div2
zar_t3 = calc_combed_zar(lgthMA3)
zar_mix = zar_t1 + zar_t2 + zar_t3

usd_t1 = calc_combed_usd(lgthMA1) / div1
usd_t2 = calc_combed_usd(lgthMA2) / div2
usd_t3 = calc_combed_usd(lgthMA3)
usd_mix = usd_t1 + usd_t2 + usd_t3

jpy_t1 = calc_combed_jpy(lgthMA1) / div1
jpy_t2 = calc_combed_jpy(lgthMA2) / div2
jpy_t3 = calc_combed_jpy(lgthMA3)
jpy_mix = jpy_t1 + jpy_t2 + jpy_t3

mix = jpy_mix * bal + usd_mix * nbal

hline(0, color=#00ff00)

plot(jpy_mix, color=blue, linewidth=2, title="EUR KI")

plot(usd_mix, color=red, linewidth=2, title="USD KI")

plot(mix, color=#ffaa00, linewidth=2, title="MIX KI X 2")
plot(alma(mix, 14, 0.86, 6), color=#ffff00, linewidth=1, title="MIX KI X 2")
lalma = alma(mix, 100, 0.99, 9)
plot(lalma, color= rising(lalma,1) ? #77ff00 : #ff7700, linewidth=2, title="MIX KI X 3")
