study("EURUSD KRIVO DBL IX", shorttitle="KRIX-EUR+USD")

src = hlc3
lgthMA1 = input(50)
lgthMA2 = input(200)
lgthMA3 = input(500)

// EUR
ex1 = security("FX:EURAUD", period, src)
ex2 = security("FX:EURPLN", period, src)
ex3 = security("FX:EURCAD", period, src)
ex4 = security("FX:EURSEK", period, src)
ex5 = security("FX:EURCHF", period, src)
ex6 = security("FX:EURTRY", period, src)
ex7 = security("FX:EURCZK", period, src)
ex8 = security("FX:EURUSD", period, src)
ex9 = security("FX:EURDKK", period, src)
ex10 = security("FX:EURGBP", period, src)
ex11 = security("FX:EURHUF", period, src)
ex12 = security("FX:EURJPY", period, src)
ex13 = security("FX:EURNOK", period, src)
ex14 = security("FX:EURNZD", period, src)

// USD
xu1=security("FX:AUDUSD", period, src)
xu2=security("FX:EURUSD", period, src)
xu3=security("FX:GBPUSD", period, src)
xu4=security("FX:NZDUSD", period, src)

ux1=security("FX:USDCHF", period, src)
ux2=security("FX:USDDKK", period, src)
ux3=security("FX:USDCAD", period, src)
ux4=security("FX:USDJPY", period, src)
ux5=security("FX:USDPLN", period, src)
ux6=security("FX:USDSEK", period, src)
ux7=security("FX:USDNOK", period, src)
ux8=security("FX:USDHUF", period, src)
ux9=security("FX:USDTRY", period, src)
ux10=security("FX:USDCZK", period, src)
ux11=security("FX:USDSGD", period, src)
ux12=security("FX:USDCNH", period, src)

lgc(s, l) =>
    ma = ema(s, l)
    s >= ma ? 1 : -1
    //d = s - ma
    //d / sma(abs(d), 2000)

nlgc(s, l) => -lgc(s, l)

calc_combed_eur(l) =>
    (lgc(ex1, l) + lgc(ex2, l) + lgc(ex3, l) + lgc(ex4, l) +
        lgc(ex5, l) + lgc(ex6, l) + lgc(ex7, l) + lgc(ex8, l) +
        lgc(ex9, l) + lgc(ex10, l) + lgc(ex11, l) + lgc(ex12, l) +
        lgc(ex13, l) + lgc(ex14, l)) / 14

calc_combed_usd(l) =>
    -(nlgc(xu1, l) + nlgc(xu2, l) + nlgc(xu3, l) + nlgc(xu4, l) +
        lgc(ux1, l) + lgc(ux2, l) + lgc(ux3, l) + lgc(ux4, l) +
        lgc(ux5, l) + lgc(ux6, l) + lgc(ux7, l) + lgc(ux8, l) +
        lgc(ux9, l) + lgc(ux10, l) + lgc(ux11, l) + lgc(ux12, l)) / 16

div1 = 8
div2 = 2
bal = 0.5
nbal = 1 - bal

// Calculate KI
usd_t1 = calc_combed_usd(lgthMA1) / div1
usd_t2 = calc_combed_usd(lgthMA2) / div2
usd_t3 = calc_combed_usd(lgthMA3)
usd_mix = usd_t1 + usd_t2 + usd_t3

// Calculate KI
eur_t1 = calc_combed_eur(lgthMA1) / div1
eur_t2 = calc_combed_eur(lgthMA2) / div2
eur_t3 = calc_combed_eur(lgthMA3)
eur_mix = eur_t1 + eur_t2 + eur_t3

mix = eur_mix * bal + usd_mix * nbal

hline(0, color=#00ff00)

plot(eur_mix, color=blue, linewidth=2, title="EUR KI")

plot(usd_mix, color=red, linewidth=2, title="USD KI")

plot(mix, color=#ffaa00, linewidth=2, title="MIX KI X 2")
plot(alma(mix, 14, 0.86, 6), color=#ffff00, linewidth=1, title="MIX KI X 2")
lalma = alma(mix, 100, 0.99, 9)
plot(lalma, color= rising(lalma,1) ? #77ff00 : #ff7700, linewidth=2, title="MIX KI X 3")
