study(title="MACD-Z", shorttitle="MACD-Z")
source = close

// Settings for 10m HEIKEN ASHI candle source!!
fastLength = input(7, minval=1)
slowLength = input(18,minval=1)
signalLength = input(6,minval=1)
fastOfs = input(0.85)
slowOfs = input(0.65)
fastSigma = input(5)
slowSigma = input(3)
signalOfs = input(0.85)
signalSigma = input(4)
sellThresh = input(-0.1)
buyThresh = input(-0.35)

fastMA = alma(source, fastLength, fastOfs, fastSigma)
slowMA = alma(source, slowLength, slowOfs, slowSigma)

macd = fastMA - slowMA
signal = alma(macd, signalLength, signalOfs, signalSigma)
hist = macd - signal

a1 = macd - macd[1]
a2 = signal - signal[1]
histexed = hist + a1 * 2 - a2
//hist *

plot(histexed, color=histexed > histexed[1] ? #009900 : #990000, style=histogram)

plot(hist, color=hist > hist[1] ? #00ff00 : #ff0000, style=line)

viewfact = 2
//thresh = 2
//thresh = max(0, -(histexed - highest(histexed, 10)))
thresh = max(0, histexed - ema(histexed, 10))
plot(thresh, color=#999999)

contrast = (a1 - a2)
//plot(contrast < -thresh and contrast < -1 and a1 < -0.5 and hist < avghist*2 and avghist > 7 ? contrast*viewfact: na, color= red, style=circles, linewidth=2)
plot(contrast < -1 and a1 < -0 ? contrast*viewfact: na, color= black, style=circles, linewidth=2)

isBuy = (macd - signal > buyThresh and macd[1] - signal[1] < buyThresh)
    or (macd - signal > buyThresh and macd[1] - signal[1] < sellThresh)

isSell = (macd - signal < sellThresh and macd[1] - signal[1] > sellThresh)
    or (macd - signal < sellThresh and macd[1] - signal[1] > buyThresh)


// WARNING! threshold and velo is in CURRENCY - NOT PERCENTS!!! MAKE A WDIF() FUNCTION! (translate to 0)

velo_thresh = 0.8
velo_compare_backlen = 5

sigvelo = (signal - signal[1])
macvelo = (macd  - macd[1])
//plot(macvelo * 10, color=purple) //DEBUG
isSell2 = macvelo < velo_thresh and macvelo < macvelo[1] and lowest(macvelo, velo_compare_backlen) > 10 * macvelo  //and sigvelo < velo_thresh and sigvelo < sigvelo[1]
isBuy2 = macvelo > -velo_thresh and macvelo > macvelo[1] and highest(macvelo, velo_compare_backlen) < 10 * macvelo  //and sigvelo > -velo_thresh and sigvelo > sigvelo[1]


bgcolor(isBuy ? #00ff00 : isSell ? #ff0000 : na, transp=50)
//plotshape(isBuy, "Buy", location = location.top, style = shape.triangleup, color=#00ff00, transp=0)
//plotshape(isSell, "Sell", location = location.top, style = shape.triangledown, color=#ff0000, transp=0)
//plotarrow(isBuy, "buy",green, red, transp=0)
//plotarrow(isSell, "sell", green,red, transp=0)
plot(isBuy ? macd : na, style=circles, color=green, linewidth=3)
plot(isSell ? macd : na, style=circles, color=red, linewidth=3)

plot(macd, color=blue)
plot(signal, color=orange)


plot(isSell2 and not isBuy2 ? signal * 1.02 : na, color=#ff0000, style=circles, linewidth = 3)
plot(isBuy2 and not isSell2 ? signal * 1.02 : na, color=#00ff00, style=circles, linewidth = 3)
