study(title = "RS/MF @XBT")

rsilen_raw = input(9, 'rsi')
tsishortlen_raw = input(2, 'tsi s')
tsilonglen_raw = input(8, 'tsi l')
mfi_len_raw = input(14, 'mfi')

period_multer = input(4, 'len multer')

rsilen = rsilen_raw * period_multer
tsishortlen = tsishortlen_raw * period_multer
tsilonglen = tsilonglen_raw // * period_multer
mfi_len = mfi_len_raw * period_multer

tsi_scaler = tsishortlen_raw / tsilonglen_raw * 0.618


volume_ = security('HUOBI:BTCCNY + BTCCHINA:BTCCNY + BTCE:BTCUSD + BITFINEX:BTCUSD + BITSTAMP:BTCUSD', period, volume)
//volume_ = security('BITSTAMP:BTCUSD + BITFINEX:BTCUSD', period, volume)
//volume_ = security('BITSTAMP:BTCUSD', period, volume)
//volume_selected_ = security('BTCE:BTCUSD + BITSTAMP:BTCUSD', period, volume)
volume_selected_ = security('BTCE:BTCUSD + BITSTAMP:BTCUSD + BITFINEX:BTCUSD', period, volume)
//close_ = security('BTCCHINA:BTCCNY / FX:USDCNH + BTCE:BTCUSD + BITSTAMP:BTCUSD', period, close)
close_ = security('BITSTAMP:BTCUSD + BITFINEX:BTCUSD', period, close)
//hlc3_ = security('BTCCHINA:BTCCNY / FX:USDCNH + BTCE:BTCUSD + BITSTAMP:BTCUSD', period, hlc3)
//hlc3_ = security('BITSTAMP:BTCUSD + BITFINEX:BTCUSD', period, hlc3)

// Calculate MF
mfi(p, v, len) =>
    raw = p * v
    posf = p > p[1] ? raw : 0
    negf = p < p[1] ? raw : 0
    posfback = sum(posf, len)
    negfback = sum(negf, len)
    100 - 100 / (1 + (posfback / negfback))

mfci(p, v, len) =>
    raw = abs(p - p[1]) * v
    posf = p > p[1] ? raw : 0
    negf = p < p[1] ? raw : 0
    posfback = sum(posf, len)
    negfback = sum(negf, len)
    100 - 100 / (1 + (posfback / negfback))

//mfiv = mfi(hlc3_, volume_, mfi_len) - 50
//mfiv2 = mfi(hlc3_, volume_selected_, mfi_len) - 50
mfiv = mfi(close_, volume_, mfi_len) - 50
mfiv2 = mfi(close_, volume_selected_, mfi_len) - 50
mfciv = mfci(close_, volume_, mfi_len) - 50
mfciv2 = mfci(close_, volume_selected_, mfi_len) - 50

rsiv = rsi(close_, rsilen) - 50 //45
tsiv = tsi(close_, tsishortlen, tsilonglen) * 100 * tsi_scaler//100
med = (rsiv + tsiv) / 2

delta = tsiv - rsiv
//delta9 = ema(delta, 9)
//plot(delta, color=yellow)
//macd9 = delta-delta9
//dispval = macd9
dispval = delta / 2
stilldays = 1
histma = ema(dispval, 6 * stilldays)
//plot(delta9, color=orange)

pl_c = hline(0, color=#000000)
pl_h = hline(30, color=#aaaaaa)
pl_l = hline(-30, color=#aaaaaa)
pl_ch = hline(20, color=#aaaaaa)
pl_cl = hline(-20, color=#aaaaaa)
hline(10, color=#aaaaaa)
hline(-10, color=#aaaaaa)

fill(pl_c, pl_l, color=#ff7777, transp=85)
fill(pl_c, pl_h, color=#77ff77, transp=85)
fill(pl_l, pl_cl, color=#ff7777, transp=85)
fill(pl_h, pl_ch, color=#77ff77, transp=85)

//falling = med[1] >= med and rsiv[1] >= rsiv and tsiv[1] >= tsiv
//rising = med[1] <= med and rsiv[1] <= rsiv and tsiv[1] <= tsiv
//medbase = (abs(lowest(med,300)) + abs(highest(med,300))) / 2
//mednormed = abs(med) / medbase
//meddiff = abs(mednormed - mednormed[1])
//med_d = meddiff //log(meddiff)
//significant = med_d > 0.15

plot(rsiv, color=#00ff00, style=line)
plot(rsiv, color=#00ff00, style=circles)
plot(tsiv, color=#00ffff, style=line)
plot(tsiv, color=#00ffff, style=circles)

mf1_pl = plot(mfiv, color=#ff0000)
mf2_pl = plot(mfiv2, color=#ff0099)
fill(mf1_pl, mf2_pl, color=#ff0099, transp=80)
plot(alma(mfiv, 10, 0.85, 6), color=#ffaa00)

plot(mfciv, color=#5500aa)
plot(mfciv, color=#5500aa, style=circles)
plot(mfciv2, color=#aa0055)
plot(mfciv2, color=#aa0055, style=circles)

//mid = (rsiv + tsiv + mfiv + mfiv2) / 4
//plot(mid, color=#444444)
//plot(mid > mfiv or mid > mfiv2 ? mid : na, color=#444444, style = circles, linewidth = 2)


//histmabase = highest(abs(histma), 500)
//histmanormed = histma /  histmabase
//histv = histmanormed - histmanormed[1] // max((histmanormed - histmanormed[1]) / histmanormed, 0.5)
//plot(histmanormed*100, color=#777777, style=line)
//plot(histv*100, color=#333333, style=line)
//stillness = abs(histv) < 0.10 and abs(histmanormed) < 0.07
//stillcolor = stillness ? #ff0000 : #aaaaaa

//plot(dispval, color=stillcolor, style=line)
//plot(dispval, color=stillcolor, style=histogram, linewidth=1)

//plot(med_d*100, color=stillness ? #ff0000 : significant ? #7777ff : #ccccff, style=cross)

//plot(med, color=#ffff00, style=line)
//plot(significant ? med : na, color= falling ? #ff0000: rising ? #00aa00 : #ffff00, style=cross, linewidth= 2)
//plot(not significant ? med : na, color= falling ? #ff0000: rising ? #00aa00 : #ffff00, style=cross, linewidth= 1)
